version: '3.8'

services:
  freshdesk-mcp-server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - FRESHDESK_DOMAIN=${FRESHDESK_DOMAIN}
      - FRESHDESK_MCP_SERVER_PORT=5000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:5000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
